---
# tasks file for mate-install

- name: Install python ...
  apt: name={{ item }} state=present
  with_items:
    - python2.7
    - python3
    - python-apt
    - python-pip
    - python3-pip

- name: Install python-apt to can add ppa repository ...
  apt: name=python-apt state=present

  # Add repositorys, keys and ppa's
- name: Add gns3 ppa ...
  apt_repository: repo=ppa:gns3/ppa state=present

- name: Add musescore ppa ...
  apt_repository: repo=ppa:mscore-ubuntu/mscore-stable state=present

- name: Add docker keys ...
  apt_key: url="https://yum.dockerproject.org/gpg" state=present

- name: Add docker repository ...
  apt_repository: repo="deb https://apt.dockerproject.org/repo/ ubuntu-xenial main" state=present

- name: Add java repository ...
  apt_repository: repo=ppa:webupd8team/java state=present


  # Update repository

- name: Update repository ...
  apt: update_cache=yes

  # Install packages

- name: Install git ...
  apt: name=git state=present

- name: Install vim ...
  apt: name=vim state=present

- name: Install tmux ...
  apt: name=tmux state=present

- name: Install bridge-utils ...
  apt: name=bridge-utils state=present

- name: Install lxc ...
  apt: name=lxc state=present

- name: Install qemu ...
  apt: name={{item}} state=present
  with_items:
    - qemu
    - qemu-kvm
    - libvirt-bin

- name: Install virt-manager
  apt: name=virt-manager state=present

- name: Install kvm ...
  apt: name=kvm state=present

- name: Install nftables ...
  apt: name=nftables state=present

- name: Install ebtables ...
  apt: name=ebtables state=present

- name: Install virtualbox ...
  apt: name=virtualbox state=present

- name: Install openvswitch-switch
  apt: name=openvswitch-switch state=present

- name: Install wireshark ...
  apt: name=wireshark state=present

- name: Install gedit ...
  apt: name=gedit state=present

- name: Install htop ...
  apt: name=htop state=present

- name: Install bmon ...
  apt: name=bmon state=present

- name: Install terminator ...
  apt: name=terminator state=present

- name: Install pavucontrol
  apt: name=pavucontrol state=present

  # CHANGE to primary shell
- name: Install fish ...
  apt: name=fish state=present

- name: Modify default shell ...
  user: name={{ ansible_ssh_user }} shell=/usr/bin/fish

- name: Copy config.fish ...
  template: src=config.fish.j2 dest="{{lookup('env','HOME')}}/.config/fish/config.fish"

  # Install repositoy
- name: Install gns3 ...
  apt: name={{ item }} state=present
  with_items:
    - gns3-gui
    - gns3-iou

- name: Install musescore ...
  apt: name=musescore state=present

- name: Install docker ...
  apt: name=docker-engine state=present

- name: Download Nodejs 7.x ...
  get_url: url="https://deb.nodesource.com/setup_7.x" dest=/tmp/nodejs.sh

- name: Change permission to execute ...
  file: path=/tmp/nodejs.sh mode="u=rwx,g=rx,o=rx"

- name: Execute nodejs.sh ...
  shell: /tmp/nodejs.sh

- name: Install nodejs ...
  apt: name=nodejs state=present

#- name: Install java 7 ...
#  apt: name=oracle-java7-installer state=present
- name: Download eclipse-neon ...
  get_url: url="http://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/neon/2/eclipse-java-neon-2-linux-gtk-x86_64.tar.gz" dest=/tmp/eclipse-neon.tar.gz

- name: Unzip eclipse-neon
  unarchive: src=/tmp/eclipse-neon.tar.gz dest=/opt/

- name: Create eclipse-neon symbolic link to /usr/bin/ ...
  file: src=/opt/eclipse/eclipse dest=/usr/bin/eclipse state=link

- name: Download pycharm ...
  get_url: url="https://download.jetbrains.com/python/pycharm-community-2016.3.2.tar.gz" dest=/tmp/pycharm.tar.gz

- name: Unzip pycharm ...
  unarchive: src=/tmp/pycharm.tar.gz dest=/opt/

- name: Create pycharm symbolic link to /usr/bin/ ...
  file: src=/opt/pycharm-community-2016.3.2/bin/pycharm.sh dest=/usr/bin/pycharm state=link

- name: Download android-studio ...
  get_url: url="https://dl.google.com/dl/android/studio/ide-zips/2.2.3.0/android-studio-ide-145.3537739-linux.zip" dest=/tmp/android-studio.zip

- name: Unzip android-studio ...
  unarchive: src=/tmp/android-studio.zip dest=/opt/

- name: Create android-studio symbolic link to /usr/bin/ ...
  file: src=/opt/android-studio/bin/studio.sh dest=/usr/bin/studio state=link

- name: Download atom ...
  get_url: url="https://atom.io/download/deb" dest=/tmp/atom.deb

- name: Install atom ...
  apt: deb=/tmp/atom.deb
